fix(version): Update the OL version
ImagingDataCommons/dicom-microscopy-viewer pull request #118
Opened 2024-05-01 18:14 UTC by wayfarer3130

Update the versions.  Also want to commit it with a fix message to force  build/release cycle.

2024-05-01 18:19 UTC, igoroctaviano commented
@wayfarer3130 I tried using this OL version before with SLIM and it has breaking changes. We might be able to merge the other changes but major OL updates would require more effort to test.

2024-05-08 11:51 UTC, igoroctaviano requested changes
LGTM, left one comment

2024-05-08 11:51 UTC, igoroctaviano commented on package.json
> +    "clean": "rm -rf ./dist",
I would rather stay with a single clean script that does it all. If people are using clean as it is, this could break their expectations.

2024-05-28 16:44 UTC, wayfarer3130 commented
@igoroctaviano - I have addressed your comment, as well as created
https://github.com/OHIF/Viewers/pull/4016
that specifically has your changes in it.

2024-05-28 16:55 UTC, igoroctaviano approved these changes
LGTM

2024-05-28 16:55 UTC, merged