feat: monitor bulk ann downloads
ImagingDataCommons/dicom-microscopy-viewer pull request #150
Opened 2024-10-10 00:04 UTC by pedrokohler

2024-10-15 19:55 UTC, igoroctaviano requested changes

2024-10-15 19:55 UTC, igoroctaviano commented on src/viewer.js
> +      console.log('AnnotationGroupUID:', metadataItem.AnnotationGroupUID, 'NumberOfAnnotations:', numberOfAnnotations)
Do we need this log?

2024-10-15 21:03 UTC, pedrokohler commented on src/viewer.js
> +      console.log('AnnotationGroupUID:', metadataItem.AnnotationGroupUID, 'NumberOfAnnotations:', numberOfAnnotations)
Yes

2024-10-24 18:10 UTC, igoroctaviano requested changes

2024-10-24 18:10 UTC, igoroctaviano commented on src/viewer.js
> +      console.log('AnnotationGroupUID:', metadataItem.AnnotationGroupUID, 'NumberOfAnnotations:', numberOfAnnotations)
Please use debug

2024-10-24 18:10 UTC, igoroctaviano commented on src/annotation.js
> +        console.info(`Loaded ${Math.round(progressEvent.loaded / 1024 / 1024 * 100) / 100} MB from annotation group "${uid}"`)
Please use debug

2024-10-24 20:31 UTC, pedrokohler commented on src/viewer.js
> +      console.log('AnnotationGroupUID:', metadataItem.AnnotationGroupUID, 'NumberOfAnnotations:', numberOfAnnotations)
Done.

2024-10-24 20:37 UTC, igoroctaviano approved these changes
LGTM

2024-10-24 20:37 UTC, merged