Add errorinterceptor argument to propagate error to the top level app
ImagingDataCommons/dicom-microscopy-viewer pull request #85
Opened 2022-11-19 05:52 UTC by GitanjaliChhetri

Errors thrown in _viewer.js_ can now be propagated to the Slim Viewer App.
Changes needed for https://github.com/herrmannlab/slim/pull/134

2022-11-28 16:25 UTC, GitanjaliChhetri commented
@hackermd I do not seem to have permissions to add reviewers to this PR. Please know it's ready for your review. Thanks!

2022-12-12 02:05 UTC, hackermd commented on src/viewer.js
> +      this[_options].errorInterceptor = error => {throw error}}
```suggestion
      this[_options].errorInterceptor = error => {throw error}
    }
```

2022-12-12 02:19 UTC, hackermd commented on src/viewer.js
> +          'Either option "client" or option "clientMapping" must be provided.'))
Please also place closing brackets `)` on a new line.

2022-12-12 02:21 UTC, hackermd commented on src/viewer.js
> +    if(!('errorInterceptor' in options)){
```suggestion
    if(options.errorInterceptor == null){
```

2022-12-12 07:04 UTC, GitanjaliChhetri commented on src/viewer.js
> +   * @param {number[]} [options.errorInterceptor] - An error instance to propogate
Thanks for the review, @hackermd .
I have updated the documentation comments accordingly. Also, modified all error instances by assigning to a variable first.

2023-01-19 22:42 UTC, GitanjaliChhetri commented
@hackermd I have addressed the requested changes. Please let me know if this can be merged? Thank you.

2023-01-28 11:18 UTC, hackermd requested changes
Thanks @GitanjaliChhetri. The changes look good. However, the `yarn test` command currently fails for me. The error report includes a lot of linting errors that were discovered by `yarn lint`.

Unfortunately, the ["unit tests" workflow](https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/master/.github/workflows/run_unit_tests.yml) doesn't automatically get tricked for the pull request. I somehow can't add it as a required status check. cc @fedorov 
Until this issue is resolved, the checks need to be run manually locally.

2023-01-28 11:36 UTC, hackermd commented
@GitanjaliChhetri @fedorov got the status checks working.

2023-02-10 21:12 UTC, fedorov commented
@hackermd can you please re-review? Per @GitanjaliChhetri, all of your concerns should now be addressed.

2023-02-18 11:12 UTC, hackermd approved these changes

2024-05-09 20:41 UTC, igoroctaviano approved these changes

2024-05-09 20:44 UTC, merged